### ISSUE TITLE
[Suggestion] Use "Levenshtein distance" for blind signature matching

### ISSUE THREAD

**Issue by s0md3v** [stamparm/identYwaf#1]
Hi there,

I really liked the idea behind this project. Kudos!

There's a thing that can come in handy while comparing signatures to the result of the test, it's called [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance).
In simple words, it's the measure of edits required to change one string to another.

For example, The Levenshtein Distance between `cat` and `bat` is `1` because we just need to change one character to change `cat` into `bat`.
Similarly, we can calculate the Levenshtein Distance between the result and the signatures.

`fuzzywuzzy` module returns the similarty between two strings using this principle and it's very easy to use.

##### Implementation
```
from fuzzywuzzy import process
signatures = ["x..xxx....", "..x..xxxxx.x", "xxx....xxx", "...x...x..x."]
result = "x...x.x.x..."
process.extract(result, signatures, limit=2) # limit = top n matches
```
Output: `[('..x..xxxxx.x', 95), ('...x...x..x.', 95)]`

I would like to implement this with a PR if you like the idea.

**Comment by stamparm** [comment]
Levenshtein distance is useful for fuzzy matching of two sets with variable size where order needs to remain. We use it extensively in sqlmap for page comparison.

In this case, there are only two fixed size binary vectors where some kind of difference has to be calculated. Current match score is more than intuitive as it says in plain language the difference between those values (ABBA and BBBA are different at 25% of places, hence their match score is 0.75)

Usage of Levenshtein distance in this project would be like suggesting usage of logarithmic function for summing two numbers. It is simply not being done because mathematics doesn't like overcomplicating things
